Backend domain is dynamic and not hardcoded anymore
p1ngul1n0/blackbird-react pull request #2
Opened 2023-01-23 13:19 UTC by Pitastic

This is a fix for [issue 19](https://github.com/p1ngul1n0/blackbird/issues/19) from the backend Repo of blackbird.

Instead of checking against a given domain and set a variable to localhost if `false` the code now retrieves the url from the browser (`window.location.*`) and concats it to the `basePath`.

A check against the `cloudDomain` is not necessary anymore as thi leads to the very same result in `basePath`.

However, I was not able to test this code with a connected backend as I don't know how to connect backend and frontend.

The code builds fine in a node.js Docker.

2023-01-31 23:01 UTC, p1ngul1n0 requested changes
Hi @Pitastic, sorry for the delay, just tested it.

I made some changes to work properly, the correct code is below, please fix it in your PR so i can accept it.

` basePath = window.location.protocol + "//" + window.location.host + "/";`

Thanks  a lot for your contribution!

2023-02-01 09:28 UTC, Pitastic commented
Thanks for reviewing. You're right, I haven't seen that `window.location.protocol` already has colons ...

2023-02-01 20:11 UTC, p1ngul1n0 commented
Sorry, i did not properly explained how the code should be, the *IF* statement can keep as it was before, just change the *else*.

It need to be like that:

```
if (window.location.hostname == cloudDomain) {
  basePath = "https://" + cloudDomain + "/";
} else {
  basePath = window.location.protocol + "//" + window.location.host + "/";
}
```

I also added instructions in RAEADME to how to test FrontEnd code with the BackEnd.

2023-02-01 20:50 UTC, Pitastic commented
I thought about this and let the variable `cloudDomain` in there because of dependencies in other modules.

But: IF `cloudDomain` than `basePath` will be the same. With or without the IF clause, wouldn't it?

2023-02-02 11:02 UTC, p1ngul1n0 commented
Hi!

@Pitastic, i think that actually no, cause we need to construct the complete URL, if we take out the IF statement, the server URL would become:

> **blackbird-osint.herokuapp.com**

But we need it like that:

> **https://blackbird-osint.herokuapp.com/**

In my opinion is better to let as it was, with the IF statement.

2023-02-03 15:35 UTC, Pitastic commented
Understood. Thanks for reviewing an the addional README info. And sorry for the bunch of messages for just a few lines of Code 😃

2023-02-05 16:15 UTC, merged